### ISSUE TITLE
Mettre à jour le planning initial

### ISSUE THREAD

**Issue by fandolfatto** [Havachi/CPNV_ProjetC-_ARI-DCT#5]
Créer un nouveau planning avec les 3 sprints (contrairement aux 4 sprints prévus initialement) et expliquer les différences.

**Comment by 1888DCT** [comment]
Mise à jour du wiki en cous de production

**Comment by 1888DCT** [comment]
mise à jour du wiki terminée.
Différences et explications dans la page "Conclusion"
