### ISSUE TITLE
Impossible d'ouvrir un 2ème labyrinthe

### ISSUE THREAD

**Issue by fandolfatto** [Havachi/CPNV_ProjetC-_ARI-DCT#8]
Je me connecte sur le jeu, un premier labyrinthe s'affiche.
Je quitte le jeu, la fenêtre de login reste visible. Je me reconnecte avec succès. Mais ensuite, un message d'erreur s'affiche, refusant d'afficher le labyrinthe et l'interface de jeu.

[erreur.docx](https://github.com/Havachi/CPNV_ProjetC-_ARI-DCT/files/4086471/erreur.docx)

**Comment by 1888DCT** [comment]
Comme discuté le 23.01.2020 : 
Nous avons fait un labyrinthe fixe vendredi passé pour que cette semaine on puisse se concentrer sur les mouvements du joueur.

L'image étant pré-enregistrée, l'erreur n'est plus.
