### ISSUE TITLE
il n'y a aucun diagramme pour documenter le projet (diagramme de use case, diagramme de séquences, diagramme de classes)

### ISSUE THREAD

**Issue by fandolfatto** [Havachi/CPNV_ProjetC-_ARI-DCT#9]
diagramme de use case et diagramme de classes sur l'ensemble de l'application
diagramme de séquences sur une fonctionnalité du code à choisir.

**Comment by 1888DCT** [comment]
Diagramme de use case et diagramme de classe présents dans le dossier "Project Documentation"
diagramme de séquences en cours de production

Le tout sera mis en évidence sur le wiki

**Comment by 1888DCT** [comment]
Diagramme de séquence ajouté

**Comment by 1888DCT** [comment]
Wiki à jour.
Mis en évidence sur la page "Documentation"
